name: flutter_mapbox_sample
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  mapbox_maps_flutter: ^2.0.0-beta.1
  permission_handler: ^11.3.1
  font_awesome_flutter: ^10.7.0
  http: ^1.2.0
  turf: ^0.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/symbols/
    - assets/cluster/